server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

spring:
  application:
    name: service-a
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092
    bus:
      enabled: true
