server:
  port: 8761  # Стандартный порт Eureka

spring:
  application:
    name: eureka-server  # Имя сервиса в Eureka

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false  # Не регистрировать себя в Eureka
    fetch-registry: false        # Не загружать список сервисов
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

# Опционально: Настройки Actuator (для мониторинга)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics